"""Ground truth for `kma.replay`, generated by running the LIVE collector code.

    cd collector && uv run python ../analysis/tests/fixtures/replay/generate_ground_truth.py

`kma.replay.IncumbentCensus` is a PORT of `kenya_monitor.runner.hot_objects`:
the analysis project takes no dependency on the collector, and the live
function reads `now()` off the wall clock, which a replay cannot use. Port
divergence is therefore the harness's real failure mode, and asserting the port
against itself would not find it. So this script drives the actual deployed
selector over a synthetic corpus, records what it picked, and `test_replay.py`
asserts that the replay reproduces those picks from the same corpus. Two
independent implementations agreeing is evidence; one implementation agreeing
with itself is not.

HOW TIME IS HANDLED, since it is the whole trick here. `hot_objects` filters on
`now() - INTERVAL n DAY` and `current_date - INTERVAL n DAY`, so it can only
ever select as of the wall clock. Every one of its predicates is RELATIVE, so
shifting every timestamp in the corpus by a constant is exactly equivalent to
shifting `now`. For virtual pass time `t_k` this script therefore materialises a
rebased copy of the corpus - all timestamps and all `dt`/`run` path segments
moved forward by `now - t_k` - containing only the objects that existed at
`t_k`, and runs the live selector against that. The canonical corpus written
into this directory keeps the absolute timestamps, so the fixture is stable
forever rather than needing regeneration each day.

The corpus is synthetic, and the ground truth is therefore about the SELECTOR's
behaviour, not about the Kenya corpus. Object degrees span all three regimes
that matter - below the band, inside it, and above the ceiling - and objects
arrive in three collection batches so that an object first seen after pass 1
must not be selectable at pass 1.
"""

from __future__ import annotations

import json
import shutil
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

import duckdb
import pyarrow as pa
import pyarrow.parquet as pq

from kenya_monitor.runner import hot_objects
from kenya_monitor.storage import ENGAGEMENT_SCHEMA, POST_SCHEMA

HERE = Path(__file__).resolve().parent
UTC = timezone.utc

REFERENCE = datetime(2026, 9, 1, 0, 0, 0, tzinfo=UTC)

# Three passes, three hours apart. Well inside the 12-hour TTL, so every pass
# after the first must exclude what the previous ones censused - which is the
# selector behaviour most likely to be got wrong in a port.
PASS_TIMES = [REFERENCE + timedelta(hours=h) for h in (0, 3, 6)]

# Collection batches. Batch 1 lands between pass 1 and pass 2, batch 2 between
# pass 2 and pass 3, so a replay that leaks future objects selects from them too
# early and the recorded selections catch it.
BATCH_TIMES = [
    REFERENCE - timedelta(hours=1),
    REFERENCE + timedelta(hours=1, minutes=30),
    REFERENCE + timedelta(hours=4, minutes=30),
]

PARAMS = {
    "lookback_days": 2,
    # Small on purpose: at the deployed 250 every in-band object is selected on
    # the first pass and neither the ranking nor the TTL is exercised.
    "top_retweeted": 5,
    "top_conversations": 5,
    "hydrate_limit": 5,
    "band_min": 3,
    "band_max": 100,
    "refresh_hours": 12,
    "retweeters_limit": 300,
}

# (object id, amplifier degree, retweet rows held, batch)
OBJECTS = [
    ("o01", 1, 1, 0),      # below the band
    ("o02", 2, 2, 0),      # below the band
    ("o03", 3, 3, 0),      # band floor
    ("o04", 12, 4, 0),
    ("o05", 27, 6, 0),
    ("o06", 44, 5, 0),
    ("o07", 63, 7, 0),
    ("o08", 81, 3, 0),
    ("o09", 99, 2, 0),     # band ceiling
    ("o10", 100, 2, 0),    # exactly the ceiling: BETWEEN is inclusive
    ("o11", 242, 9, 0),    # hub; the range Step 7 measured on pi0
    ("o12", 900, 14, 0),   # hub, above the retweeter limit
    ("o13", 55, 4, 1),
    ("o14", 70, 6, 1),
    ("o15", 150, 8, 1),    # hub, arrives after pass 1
    ("o16", 30, 3, 1),
    ("o17", 88, 5, 2),
    ("o18", 410, 11, 2),   # hub, arrives after pass 2
]


def _post_rows() -> list[dict]:
    rows = []
    for oid, degree, n_rows, batch in OBJECTS:
        for i in range(n_rows):
            rows.append(
                {
                    "platform": "x",
                    "platform_post_id": f"rt-{oid}-{i}",
                    # Not `hash()`: PYTHONHASHSEED is randomised per process and
                    # the fixture has to be byte-reproducible.
                    "author_id": f"a{(int(oid[1:]) * 5 + i) % 40 + 1:03d}",
                    "author_handle": None,
                    "text": f"RT {oid}",
                    # Six hours before the reference, so every object stays
                    # inside the two-day created_at window for all three passes
                    # and nothing sits on a boundary.
                    "created_at": REFERENCE - timedelta(hours=6),
                    "url": None,
                    "source_query": "fixture",
                    "lang": "en",
                    "in_reply_to_id": None,
                    "is_repost": True,
                    "repost_of_id": oid,
                    "like_count": 0,
                    "reply_count": degree // 3,
                    "repost_count": degree,
                    "quote_count": 0,
                    "view_count": 0,
                    "hashtags": [],
                    "cashtags": [],
                    "mentions": [],
                    "urls": [],
                    "quoted_post_id": None,
                    "is_quote": False,
                    "conversation_id": oid,
                    "in_reply_to_user_id": None,
                    "source_label": None,
                    "place_name": None,
                    "lat": None,
                    "lon": None,
                    "has_media": False,
                    "media_count": 0,
                    "media_urls": [],
                    "collected_at": BATCH_TIMES[batch],
                }
            )
    return rows


def _retweeters(oid: str, degree: int, limit: int) -> list[str]:
    """Deterministic amplifier ids with deliberate overlap between objects, so
    the TF-IDF projection has co-amplification pairs to find."""
    n = min(degree, limit)
    base = int(oid[1:])
    return [f"u{(base * 7 + j) % 60:03d}" for j in range(n)]


# List columns cannot round-trip through CSV and no selection predicate reads
# them, so they are dropped from the checked-in corpus. Everything the selector
# or the replay touches survives.
_LIST_COLUMNS = ("hashtags", "cashtags", "mentions", "urls", "media_urls")


def _write(rows: list[dict], schema: pa.Schema, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(pa.Table.from_pylist(rows, schema=schema), path, compression="zstd")


def _write_csv(rows: list[dict], schema: pa.Schema, path: Path) -> None:
    """The corpus as CSV, because the repo gitignores `*.parquet` wholesale and
    weakening that rule to check in test data is the wrong trade - it is there
    so corpus extracts cannot be committed by accident. `test_replay.py`
    materialises these back into hive-partitioned parquet at fixture time, so
    the pinning path is still exercised against real parquet objects."""
    path.parent.mkdir(parents=True, exist_ok=True)
    table = pa.Table.from_pylist(rows, schema=schema)
    keep = [n for n in table.schema.names if n not in _LIST_COLUMNS]
    con = duckdb.connect()
    con.register("_t", table.select(keep))
    con.execute(f"COPY _t TO '{path}' (FORMAT csv, HEADER)")
    con.close()


def _key(prefix: str, when: datetime, *, type_: str | None = None) -> str:
    parts = [prefix, "platform=x"]
    if type_:
        parts.append(f"type={type_}")
    parts.append(f"dt={when.strftime('%Y-%m-%d')}")
    parts.append(f"run={when.strftime('%Y%m%dT%H%M%SZ')}.parquet")
    return "/".join(parts)


def _shift(rows: list[dict], delta: timedelta, columns: tuple[str, ...]) -> list[dict]:
    out = []
    for row in rows:
        copy = dict(row)
        for column in columns:
            if copy.get(column) is not None:
                copy[column] = copy[column] + delta
        out.append(copy)
    return out


def _glob(root: Path, prefix: str, type_: str | None = None) -> str:
    mid = f"/type={type_}" if type_ else ""
    pattern = f"{root}/{prefix}/platform=x{mid}/dt=*/run=*.parquet"
    return f"read_parquet('{pattern}', union_by_name=true, hive_partitioning=true)"


def _exists(root: Path, prefix: str) -> bool:
    return any((root / prefix).rglob("*.parquet")) if (root / prefix).exists() else False


def main() -> None:
    posts = _post_rows()
    engagement_rows: list[dict] = []
    selections: list[list[str]] = []

    corpus = HERE / "corpus"
    if corpus.exists():
        shutil.rmtree(corpus)

    for when in BATCH_TIMES:
        _write_csv(
            [r for r in posts if r["collected_at"] == when],
            POST_SCHEMA,
            corpus / (_key("posts", when, type_="search") + ".csv"),
        )

    for pass_time in PASS_TIMES:
        # The live selector can only select as of the wall clock, so rebase the
        # corpus rather than trying to move `now`.
        shift = datetime.now(UTC).replace(microsecond=0) - pass_time
        staging = Path(tempfile.mkdtemp(prefix="replay-gt-"))
        try:
            for when in BATCH_TIMES:
                if when > pass_time:
                    continue  # did not exist yet; including it would be the leak
                rows = _shift(
                    [r for r in posts if r["collected_at"] == when],
                    shift,
                    ("created_at", "collected_at"),
                )
                _write(rows, POST_SCHEMA, staging / _key("posts", when + shift, type_="search"))
            for when in sorted({r["collected_at"] for r in engagement_rows}):
                if when > pass_time:
                    continue
                rows = _shift(
                    [r for r in engagement_rows if r["collected_at"] == when],
                    shift,
                    ("collected_at",),
                )
                _write(rows, ENGAGEMENT_SCHEMA, staging / _key("engagements", when + shift))

            con = duckdb.connect()
            retweeted, _conversations, _missing = hot_objects(
                con,
                _glob(staging, "posts", "*"),
                PARAMS["lookback_days"],
                PARAMS["top_retweeted"],
                PARAMS["top_conversations"],
                PARAMS["hydrate_limit"],
                PARAMS["band_min"],
                PARAMS["band_max"],
                _glob(staging, "engagements") if _exists(staging, "engagements") else None,
                None,
                PARAMS["refresh_hours"],
            )
            con.close()
        finally:
            shutil.rmtree(staging, ignore_errors=True)

        selections.append(list(retweeted))
        print(f"{pass_time.isoformat()} -> {retweeted}")

        # Simulate the census the collector would then have run, so the next
        # pass sees the TTL exclusion it would really have seen.
        degrees = dict((oid, deg) for oid, deg, _n, _b in OBJECTS)
        censused_at = pass_time + timedelta(minutes=1)
        for oid in retweeted:
            for user in _retweeters(oid, degrees[oid], PARAMS["retweeters_limit"]):
                engagement_rows.append(
                    {
                        "platform": "x",
                        "platform_post_id": oid,
                        "platform_user_id": user,
                        "kind": "retweet",
                        "collected_at": censused_at,
                    }
                )
        _write_csv(
            [r for r in engagement_rows if r["collected_at"] == censused_at],
            ENGAGEMENT_SCHEMA,
            corpus / (_key("engagements", censused_at) + ".csv"),
        )

    ground_truth = {
        "generated_at": datetime.now(UTC).isoformat(),
        "generator": "analysis/tests/fixtures/replay/generate_ground_truth.py",
        "selector": "kenya_monitor.runner.hot_objects (retweeted arm)",
        "reference": REFERENCE.isoformat(),
        "pass_times": [t.isoformat() for t in PASS_TIMES],
        "params": PARAMS,
        "objects": [
            {"id": oid, "degree": deg, "rows": n, "batch": b} for oid, deg, n, b in OBJECTS
        ],
        "selected": selections,
    }
    (HERE / "ground_truth.json").write_text(json.dumps(ground_truth, indent=2) + "\n")
    print(f"wrote {HERE / 'ground_truth.json'}")


if __name__ == "__main__":
    main()
