"""The replay harness has one correctness property: a policy cannot see the future.

Everything else it does is bookkeeping. So these tests spend most of their
effort on the two ways a policy could see past *t* - reading an object written
later, and naming a target it had no way to know - and on the acceptance check
that the replayed incumbent reproduces what the live selector actually picked.

That ground truth comes from `fixtures/replay/`, generated by running
`kenya_monitor.runner.hot_objects` itself; see the generator's docstring for why
a port cannot be validated against itself. Everything here is offline: a git
worktree has no R2 credentials, and a local directory stands in for the bucket.
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path

import duckdb
import pandas as pd
import pytest

from kma import bench, replay

UTC = timezone.utc
FIXTURES = Path(__file__).resolve().parent / "fixtures" / "replay"


class LocalR2:
    """`list_objects_v2` over a local directory. Unpaginated - `test_bench.py`
    already covers the pagination path, and this suite is about time, not keys."""

    def __init__(self, root: Path) -> None:
        self.root = root

    def list_objects_v2(self, Bucket: str, Prefix: str, ContinuationToken: str | None = None):
        keys = sorted(
            str(p.relative_to(self.root))
            for p in self.root.rglob("*")
            if p.is_file() and str(p.relative_to(self.root)).startswith(Prefix)
        )
        return {
            "Contents": [
                {"Key": k, "Size": (self.root / k).stat().st_size, "ETag": f'"etag-{k}"'}
                for k in keys
            ],
            "IsTruncated": False,
        }


def _manifest(con: duckdb.DuckDBPyConnection, root: Path) -> pd.DataFrame:
    return bench.snapshot(
        "fixture",
        prefixes=("posts", "engagements"),
        con=con,
        client=LocalR2(root),
        uri=lambda key: f"{root}/{key}",
        write=False,
    )


@pytest.fixture
def ground_truth() -> dict:
    return json.loads((FIXTURES / "ground_truth.json").read_text())


@pytest.fixture
def corpus(tmp_path) -> tuple[duckdb.DuckDBPyConnection, Path, pd.DataFrame]:
    """The checked-in corpus, materialised into a local stand-in for the bucket.

    It is checked in as CSV because the repo gitignores `*.parquet` wholesale,
    and that rule exists so corpus extracts cannot be committed by accident -
    weakening it for test data is the wrong trade. The harness pins parquet
    objects by path, so the CSVs are converted here rather than read directly:
    `run=...parquet.csv` -> `run=...parquet`, keeping the hive layout and the
    write timestamps that dating an object depends on.
    """
    root = tmp_path / "bucket"
    con = duckdb.connect()
    for csv in sorted((FIXTURES / "corpus").rglob("*.csv")):
        target = root / csv.relative_to(FIXTURES / "corpus").with_suffix("")
        target.parent.mkdir(parents=True, exist_ok=True)
        con.execute(
            f"COPY (SELECT * FROM read_csv('{csv}', header=true)) "
            f"TO '{target}' (FORMAT parquet)"
        )
    return con, root, _manifest(con, root)


def _write_posts(con: duckdb.DuckDBPyConnection, root: Path, when: datetime, rows: list[dict]):
    """Post rows into a run object keyed by `when`, as the collector writes them."""
    frame = pd.DataFrame(rows)
    key = (
        f"posts/platform=x/type=search/dt={when:%Y-%m-%d}"
        f"/run={when:%Y%m%dT%H%M%SZ}.parquet"
    )
    path = root / key
    path.parent.mkdir(parents=True, exist_ok=True)
    con.register("_t", frame)
    con.execute(f"COPY _t TO '{path}' (FORMAT parquet)")
    con.unregister("_t")


def _write_engagements(
    con: duckdb.DuckDBPyConnection, root: Path, when: datetime, rows: list[dict]
) -> None:
    key = f"engagements/platform=x/dt={when:%Y-%m-%d}/run={when:%Y%m%dT%H%M%SZ}.parquet"
    path = root / key
    path.parent.mkdir(parents=True, exist_ok=True)
    con.register("_e", pd.DataFrame(rows))
    con.execute(f"COPY _e TO '{path}' (FORMAT parquet)")
    con.unregister("_e")


def _post(pid: str, oid: str, degree: int, author: str, created: datetime, collected: datetime):
    return {
        "platform": "x",
        "platform_post_id": pid,
        "author_id": author,
        "created_at": created,
        "is_repost": True,
        "repost_of_id": oid,
        "repost_count": degree,
        "reply_count": 0,
        "quote_count": 0,
        "quoted_post_id": None,
        "in_reply_to_id": None,
        "conversation_id": oid,
        "collected_at": collected,
    }


# --------------------------------------------------------------------------
# Keys carry their write time, which is what makes leakage preventable
# --------------------------------------------------------------------------


def test_run_timestamp_reads_the_write_time_from_the_key():
    got = replay.run_timestamp("posts/platform=x/type=search/dt=2026-09-05/run=20260905T081903Z.parquet")
    assert got == datetime(2026, 9, 5, 8, 19, 3, tzinfo=UTC)


def test_run_timestamp_is_none_for_a_key_without_one():
    assert replay.run_timestamp("bench/snapshot=s1/manifest.parquet") is None


def test_census_pass_times_groups_writes_into_passes(corpus):
    _con, _root, manifest = corpus
    times = replay.census_pass_times(manifest)
    assert len(times) == 3
    assert [t.isoformat() for t in times] == [
        "2026-09-01T00:01:00+00:00",
        "2026-09-01T03:01:00+00:00",
        "2026-09-01T06:01:00+00:00",
    ]


def test_census_pass_times_gap_decides_what_counts_as_one_pass(corpus):
    _con, _root, manifest = corpus
    # A pass flushes every 25 objects, so writes minutes apart are one pass and
    # writes hours apart are not. At a four-hour tolerance the three collapse.
    assert len(replay.census_pass_times(manifest, gap_minutes=4 * 60)) == 1


def test_census_pass_times_is_empty_without_engagements(corpus):
    con, root, _m = corpus
    shutil.rmtree(root / "engagements")
    assert replay.census_pass_times(_manifest(con, root)) == []


# --------------------------------------------------------------------------
# Clipping: the harness's whole correctness property
# --------------------------------------------------------------------------


def test_clipped_source_excludes_objects_written_after_t(corpus):
    con, _root, manifest = corpus
    early = replay.clipped_source(manifest, "posts", datetime(2026, 9, 1, 0, 0, tzinfo=UTC))
    late = replay.clipped_source(manifest, "posts", datetime(2026, 9, 2, tzinfo=UTC))
    assert early.count("run=") == 1
    assert late.count("run=") == 3
    assert con.sql(f"SELECT count(*) FROM {early}").fetchone()[0] < con.sql(
        f"SELECT count(*) FROM {late}"
    ).fetchone()[0]


def test_clipped_source_also_clips_rows_inside_an_admitted_object(corpus):
    """Object-level pinning is not enough: the collector flushes mid-pass, so a
    single object can hold rows from both sides of `t`."""
    con, root, _m = corpus
    written = datetime(2026, 9, 3, 12, 0, tzinfo=UTC)
    created = datetime(2026, 9, 3, 6, 0, tzinfo=UTC)
    _write_posts(
        con,
        root,
        written,
        [
            _post("straddle-early", "sx", 9, "a1", created, written - timedelta(minutes=20)),
            _post("straddle-late", "sx", 9, "a2", created, written + timedelta(minutes=20)),
        ],
    )
    manifest = _manifest(con, root)
    mid = written + timedelta(minutes=1)
    src = replay.clipped_source(manifest, "posts", mid)
    ids = {r[0] for r in con.sql(f"SELECT platform_post_id FROM {src}").fetchall()}
    assert "straddle-early" in ids
    assert "straddle-late" not in ids


def test_clipped_source_is_none_when_nothing_predates_t(corpus):
    _con, _root, manifest = corpus
    assert replay.clipped_source(manifest, "posts", datetime(2020, 1, 1, tzinfo=UTC)) is None


def test_clipped_source_drops_objects_whose_write_time_is_unreadable(corpus):
    """An object that cannot be dated cannot be proven to predate `t`, so it is
    excluded. Admitting it is how leakage gets in."""
    con, root, _m = corpus
    stray = root / "posts/platform=x/type=search/dt=2026-09-01/undated.parquet"
    shutil.copy(next((root / "posts").rglob("*.parquet")), stray)
    manifest = _manifest(con, root)
    src = replay.clipped_source(manifest, "posts", datetime(2026, 9, 9, tzinfo=UTC))
    assert "undated.parquet" not in src


def test_state_at_refuses_a_moment_with_no_corpus(corpus):
    con, _root, manifest = corpus
    with pytest.raises(ValueError, match="no posts"):
        replay.state_at(con, manifest, datetime(2020, 1, 1, tzinfo=UTC))


# --------------------------------------------------------------------------
# The cost model
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "degree,expected",
    [
        (0, 1),      # a fetch is at least one request
        (1, 1),
        (20, 1),
        (21, 2),
        (27, 2),     # census-tuning.md §2c prices this at 1, at 100 per page
        (300, 15),
        (900, 15),   # capped by SNOWBALL_RETWEETERS_LIMIT
    ],
)
def test_request_cost_pages_at_twenty(degree, expected):
    assert replay.IncumbentCensus().request_cost(degree) == expected


def test_request_cost_follows_the_policys_own_page_size():
    assert replay.IncumbentCensus(page_size=100).request_cost(300) == 3


def test_a_fetch_cannot_cost_less_than_one_request():
    with pytest.raises(ValueError, match="at least one request"):
        replay.FetchRequest("retweeters", "o1", 0)


# --------------------------------------------------------------------------
# THE ACCEPTANCE TEST: does the replayed incumbent reproduce what ran?
# --------------------------------------------------------------------------


def test_incumbent_replay_reproduces_the_live_selectors_picks(corpus, ground_truth):
    """The gate on the whole module. The expected lists come from running
    `kenya_monitor.runner.hot_objects` over this same corpus."""
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    policy = replay.IncumbentCensus(**{
        k: ground_truth["params"][k]
        for k in ("band_min", "band_max", "lookback_days", "top_retweeted", "refresh_hours",
                  "retweeters_limit")
    })
    result = replay.replay(
        con, policy=policy, manifest=manifest, times=times, snapshot="fixture", seed=False
    )
    got = [list(step.targets) for step in result.steps]
    assert got == ground_truth["selected"]


def test_reproduction_recall_and_precision_are_exact_on_the_fixture(corpus, ground_truth):
    con, _root, manifest = corpus
    # Pass k's selection is censused a minute later, so replay one minute before
    # each recorded engagement write - the moment the pass began.
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    policy = replay.IncumbentCensus(
        band_min=3, band_max=100, lookback_days=2, top_retweeted=5, refresh_hours=12
    )
    rep = replay.reproduce(
        con, manifest=manifest, times=times, snapshot="fixture", policy=policy
    )
    assert rep.recall == 1.0
    assert rep.precision == 1.0
    assert rep.jaccard == 1.0
    assert rep.per_pass["observed_only"].sum() == 0


def test_reproduction_carries_the_snapshot_and_the_limitation(corpus, ground_truth):
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    rep = replay.reproduce(
        con,
        manifest=manifest,
        times=times,
        snapshot="2026-09-05-promotion-off",
        policy=replay.IncumbentCensus(top_retweeted=5),
    )
    assert rep.snapshot == "2026-09-05-promotion-off"
    assert "incumbent policy" in rep.limitation


def test_a_leaking_replay_would_have_been_caught(corpus, ground_truth):
    """The reproduction check earns its keep only if it can fail. A policy given
    the whole corpus at every step selects objects that did not exist yet, and
    the recorded ground truth rejects it."""
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    end = max(times) + timedelta(days=1)
    leaky = [end, end, end]
    result = replay.replay(
        con,
        policy=replay.IncumbentCensus(top_retweeted=5),
        manifest=manifest,
        times=leaky,
        snapshot="fixture",
        seed=False,
    )
    assert [list(s.targets) for s in result.steps] != ground_truth["selected"]
    # o17 arrives in the third collection batch and cannot be selectable first.
    assert "o17" in result.steps[0].targets


# --------------------------------------------------------------------------
# Leakage by construction, and the audit that stops it
# --------------------------------------------------------------------------


class Clairvoyant:
    """A policy that names an object it has no way to know about."""

    name = "clairvoyant"

    def params(self) -> dict[str, object]:
        return {}

    def candidates(self, state: replay.ReplayState) -> list[replay.FetchRequest]:
        return [replay.FetchRequest("retweeters", "never-collected-anywhere", 1)]


def test_audit_rejects_a_target_that_was_not_observable(corpus, ground_truth):
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(ground_truth["pass_times"][0])]
    with pytest.raises(replay.Leakage, match="not observable"):
        replay.replay(
            con, policy=Clairvoyant(), manifest=manifest, times=times, snapshot="fixture"
        )


def test_the_audit_is_what_does_the_work(corpus, ground_truth):
    """Same policy, `audit=False`: it runs. So the guard is real rather than a
    property the corpus happens to have."""
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(ground_truth["pass_times"][0])]
    result = replay.replay(
        con,
        policy=Clairvoyant(),
        manifest=manifest,
        times=times,
        snapshot="fixture",
        audit=False,
    )
    assert result.targets == ["never-collected-anywhere"]


def test_audit_admits_a_referenced_but_uncollected_object(corpus, ground_truth):
    """The hydration arm legitimately asks for objects that are REFERENCED and
    not held, so the visible space is post ids plus the ids posts reference."""
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    state = replay.state_at(con, manifest, t)
    replay._audit(state, [replay.FetchRequest("hydrate", "o05", 1)])


# --------------------------------------------------------------------------
# The driver
# --------------------------------------------------------------------------


def test_replay_needs_a_time_to_step_to(corpus):
    con, _root, manifest = corpus
    with pytest.raises(ValueError, match="at least one time"):
        replay.replay(
            con, policy=replay.IncumbentCensus(), manifest=manifest, times=[], snapshot="f"
        )


def test_replay_steps_in_time_order_whatever_order_it_is_given(corpus, ground_truth):
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    policy = replay.IncumbentCensus(top_retweeted=5)
    forward = replay.replay(
        con, policy=policy, manifest=manifest, times=times, snapshot="f", seed=False
    )
    backward = replay.replay(
        con, policy=policy, manifest=manifest, times=list(reversed(times)), snapshot="f",
        seed=False,
    )
    assert [s.targets for s in forward.steps] == [s.targets for s in backward.steps]


def test_the_ttl_ledger_stops_a_re_census_inside_the_window(corpus, ground_truth):
    con, _root, manifest = corpus
    first, second = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]][:2]
    result = replay.replay(
        con,
        policy=replay.IncumbentCensus(top_retweeted=5),
        manifest=manifest,
        times=[first, second],
        snapshot="f",
        seed=False,
    )
    assert not set(result.steps[0].targets) & set(result.steps[1].targets)


def test_the_ledger_is_seeded_from_corpus_history_before_the_window(corpus, ground_truth):
    """A replay starting mid-history inherits a census. Without the seed the
    policy re-fetches completed work and inflates its request count and its
    yield together."""
    con, _root, manifest = corpus
    third = datetime.fromisoformat(ground_truth["pass_times"][2])
    seeded = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[third], snapshot="f", seed=True,
    )
    cold = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[third], snapshot="f", seed=False,
    )
    already = {oid for pass_ids in ground_truth["selected"][:2] for oid in pass_ids}
    assert not set(seeded.targets) & already
    assert set(cold.targets) & already


def test_seed_ledger_records_the_last_census_per_object(corpus, ground_truth):
    con, _root, manifest = corpus
    end = datetime.fromisoformat(ground_truth["pass_times"][2]) + timedelta(hours=1)
    ledger = replay.seed_ledger(con, manifest, end)
    censused = {oid for pass_ids in ground_truth["selected"] for oid in pass_ids}
    assert set(ledger) == censused


def test_budget_truncates_in_the_policys_own_rank_order(corpus, ground_truth):
    """A rate-limit abort truncates the tail of a pass, not a random subset."""
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    full = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[t], snapshot="f", seed=False,
    )
    capped = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[t], snapshot="f", seed=False, budget=10,
    )
    assert capped.planned_requests <= 10 < full.planned_requests
    assert capped.targets == full.targets[: len(capped.targets)]


def test_every_result_carries_its_snapshot_id_and_the_limitation(corpus, ground_truth):
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    result = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[t], snapshot="2026-09-05-promotion-off", seed=False,
    )
    assert result.snapshot == "2026-09-05-promotion-off"
    assert result.limitation == replay.LIMITATION
    frame = result.to_frame()
    assert set(frame["snapshot"]) == {"2026-09-05-promotion-off"}
    assert frame["limitation"].str.contains("incumbent").all()


def test_the_incumbent_satisfies_the_policy_protocol():
    assert isinstance(replay.IncumbentCensus(), replay.Policy)
    assert isinstance(replay.UnbandedCensus(), replay.Policy)


# --------------------------------------------------------------------------
# B3 candidate: the band's upper bound
# --------------------------------------------------------------------------


def test_the_incumbent_band_excludes_both_tails(corpus, ground_truth):
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    picked = set(
        replay.replay(
            con, policy=replay.IncumbentCensus(top_retweeted=50), manifest=manifest,
            times=[t], snapshot="f", seed=False,
        ).targets
    )
    below = {o["id"] for o in ground_truth["objects"] if o["degree"] < 3}
    above = {o["id"] for o in ground_truth["objects"] if o["degree"] > 100}
    assert not picked & below
    assert not picked & above
    assert "o10" in picked  # BETWEEN is inclusive at the ceiling


def test_the_unbanded_candidate_reaches_the_hubs_the_incumbent_refuses(corpus, ground_truth):
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    candidate = replay.UnbandedCensus(top_retweeted=50)
    picked = set(
        replay.replay(
            con, policy=candidate, manifest=manifest, times=[t], snapshot="f", seed=False
        ).targets
    )
    hubs = {o["id"] for o in ground_truth["objects"] if o["degree"] > 100 and o["batch"] == 0}
    assert hubs <= picked
    assert candidate.params()["band_max"] is None


def test_the_unbanded_candidate_still_honours_the_band_floor(corpus, ground_truth):
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    picked = set(
        replay.replay(
            con, policy=replay.UnbandedCensus(top_retweeted=50), manifest=manifest,
            times=[t], snapshot="f", seed=False,
        ).targets
    )
    assert not picked & {o["id"] for o in ground_truth["objects"] if o["degree"] < 3}


def test_hubs_cost_more_requests_than_in_band_objects(corpus, ground_truth):
    """Which is the trade the metric exists to price: a hub buys more accounts
    per object and costs up to 15 requests to get them."""
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    base = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[t], snapshot="f", seed=False,
    )
    cand = replay.replay(
        con, policy=replay.UnbandedCensus(top_retweeted=5), manifest=manifest,
        times=[t], snapshot="f", seed=False,
    )
    assert cand.planned_requests > base.planned_requests


# --------------------------------------------------------------------------
# B2: the metric
# --------------------------------------------------------------------------


def test_score_counts_fused_edges_per_request(corpus, ground_truth):
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    result = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=times, snapshot="fixture", seed=False,
    )
    got = replay.score(con, manifest, result)
    assert got.edges > 0
    assert got.users > 0
    assert got.planned_requests == result.planned_requests
    assert got.edges_per_request == pytest.approx(got.edges / got.planned_requests)


def test_score_prices_the_realised_fetch_from_the_incidence_that_came_back(corpus, ground_truth):
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    result = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=[t], snapshot="fixture", seed=False,
    )
    got = replay.score(con, manifest, result)
    # Planned cost is priced off `repost_count`, a platform counter; realised
    # cost is priced off the DISTINCT accounts that came back. The fixture draws
    # amplifiers from a pool of 60, so its denser objects return fewer accounts
    # than their counter claims - which is the same direction real data
    # diverges, and the reason both numbers are reported instead of one.
    assert 0 < got.realised_requests < got.planned_requests
    assert got.edges_per_realised_request > got.edges_per_request


def test_score_reports_requests_it_cannot_score(corpus, ground_truth):
    """The incumbent-bias statement, as a number. An object the census never
    covered has no incidence in the corpus, so the harness can only return zero
    for it - and says so rather than folding it into the denominator silently."""
    con, _root, manifest = corpus
    t = datetime.fromisoformat(ground_truth["pass_times"][0])
    cand = replay.replay(
        con, policy=replay.UnbandedCensus(top_retweeted=50), manifest=manifest,
        times=[t], snapshot="fixture", seed=False,
    )
    got = replay.score(con, manifest, cand)
    assert got.unscorable_targets > 0
    assert 0.0 < got.unscorable_share < 1.0
    assert got.as_row()["limitation"] == replay.LIMITATION


def test_score_applies_the_v2_activity_floor(corpus):
    """A user acting on one entity cannot express coordination: two users whose
    only action is the same object have identical one-hot TF-IDF vectors, so
    their cosine is 1.0 whatever IDF does (`coord2.MIN_ENTITIES_PER_USER`). A
    policy that buys nothing but such users has bought no edges, and the metric
    must not credit it with a clique."""
    con, root, _m = corpus
    when = datetime(2026, 9, 2, 12, 0, tzinfo=UTC)
    _write_engagements(
        con,
        root,
        when,
        [
            {
                "platform": "x",
                "platform_post_id": "single",
                "platform_user_id": f"once-{i}",
                "kind": "retweet",
                "collected_at": when,
            }
            for i in range(3)
        ],
    )
    manifest = _manifest(con, root)
    result = replay.ReplayResult(
        snapshot="fixture",
        policy="hand-built",
        params={},
        steps=[
            replay.StepRecord(
                t=when, requested=1, requests=1, targets=("single",), degrees=(1,)
            )
        ],
    )
    assert replay.score(con, manifest, result, min_entities=2).edges == 0
    assert replay.score(con, manifest, result, min_entities=1).edges == 3


def test_score_of_nothing_is_zero_not_an_error(corpus):
    con, _root, manifest = corpus
    empty = replay.ReplayResult(snapshot="fixture", policy="none", params={}, steps=[])
    got = replay.score(con, manifest, empty)
    assert (got.edges, got.users, got.planned_requests, got.edges_per_request) == (0, 0, 0, 0.0)


def test_census_incidence_deduplicates_repeat_sightings(corpus, ground_truth):
    """Engagements carry no tombstones, so an edge seen twice is one edge."""
    con, _root, manifest = corpus
    censused = [oid for pass_ids in ground_truth["selected"] for oid in pass_ids]
    traces = replay.census_incidence(con, manifest, censused)
    assert len(traces) == len(traces.drop_duplicates())
    assert set(traces["entity"]) == set(censused)


def test_census_incidence_of_an_uncensused_object_is_empty(corpus):
    con, _root, manifest = corpus
    assert replay.census_incidence(con, manifest, ["o11", "o12"]).empty


def test_compare_reports_the_ratio_and_the_limitation_on_every_row(corpus, ground_truth):
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    base = replay.replay(
        con, policy=replay.IncumbentCensus(top_retweeted=5), manifest=manifest,
        times=times, snapshot="fixture", seed=False,
    )
    cand = replay.replay(
        con, policy=replay.UnbandedCensus(top_retweeted=5), manifest=manifest,
        times=times, snapshot="fixture", seed=False,
    )
    frame = replay.compare(con, manifest, base, cand)
    assert list(frame["policy"]) == ["incumbent", "unbanded"]
    assert frame["ratio_vs_baseline"].iloc[0] == 1.0
    assert frame["limitation"].eq(replay.LIMITATION).all()
    assert set(frame["snapshot"]) == {"fixture"}


def test_the_metric_is_deterministic_given_the_snapshot(corpus, ground_truth):
    """The noise floor of a replay comparison is zero, and that is the claim any
    quoted delta rests on. Nothing here samples, shuffles or times, so a
    repeated run must agree exactly - unlike the ~20% band on a real collection
    pass, which is what the plan's three-runs-both-orders rule was written for."""
    con, _root, manifest = corpus
    times = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]]
    scores = [
        replay.score(
            con,
            manifest,
            replay.replay(
                con, policy=replay.UnbandedCensus(top_retweeted=5), manifest=manifest,
                times=times, snapshot="fixture", seed=False,
            ),
        ).as_row()
        for _ in range(3)
    ]
    assert scores[0] == scores[1] == scores[2]


def test_observed_fetches_window_is_half_open(corpus, ground_truth):
    """[start, end): a pass's fetches belong to that pass and not to the next."""
    con, _root, manifest = corpus
    first, second = [datetime.fromisoformat(t) for t in ground_truth["pass_times"]][:2]
    got = replay.observed_fetches(con, manifest, first, second)
    assert got == set(ground_truth["selected"][0])
    assert replay.observed_fetches(con, manifest, first, first) == set()


def test_seed_ledger_prefers_the_recorded_ttl_over_inference(tmp_path):
    """`census_ttl/` is exact; inferring from engagement writes is not.

    An object selected that returned no retweeters writes no engagement row, so
    inference marks it un-censused and the policy re-selects it while the live
    collector skipped it on TTL. With 69.4% of objects re-censused on a 12-hour
    TTL (measured 2026-09-08), that error moves a large share of each pass.
    """
    import duckdb
    import pandas as pd

    from kma import replay

    con = duckdb.connect()
    ttl = tmp_path / "ttl.parquet"
    eng = tmp_path / "eng.parquet"

    # The ledger knows about an object that left NO engagement row.
    con.execute(
        "COPY (SELECT 'empty-obj' AS object_id, "
        "'2026-09-08T10:00:00+00:00' AS censused_at) "
        f"TO '{ttl}' (FORMAT parquet)"
    )
    con.execute(
        "COPY (SELECT 'other-obj' AS platform_post_id, "
        "TIMESTAMPTZ '2026-09-08 09:00:00+00' AS collected_at) "
        f"TO '{eng}' (FORMAT parquet)"
    )

    manifest = pd.DataFrame(
        [
            {"prefix": "census_ttl", "path": str(ttl), "platform": "x",
             "key": "census_ttl/platform=x/dt=2026-09-08/run=20260908T100000Z.parquet"},
            {"prefix": "engagements", "path": str(eng), "platform": "x",
             "key": "engagements/platform=x/dt=2026-09-08/run=20260908T090000Z.parquet"},
        ]
    )

    t = pd.Timestamp("2026-09-08 12:00:00+00:00").to_pydatetime()
    seeded = replay.seed_ledger(con, manifest, t)

    assert "empty-obj" in seeded, "the recorded ledger must win over inference"
    assert "other-obj" not in seeded, "inference must not be mixed in when the ledger exists"
